name: ECSync
description: Syncs player 'tags' to the forum software.
author: Emil Ekstrom aka Uncle_Emil. On bukkit forums known as Ekstemi
website: http://ekstemicraft.com
main: com.ekstemicraft.plugin.ecsync.ECSync
version: 2.0
commands:
   sync:
      description: Sync player group to forum.
      usage: /<command> [player]
   verify:
      description: Verify player registration
      usage: /<command>
permissions:
    ecsync.receive:
        description: Access to ECSync receive messages.
    ecsync.dontremind:
        description: Doesnt do the guest remainding for the player/group
  
  