name: ECSync
description: Syncs player 'tags' to the forum software.
author: Emil Ekstrom aka Uncle_Emil. On bukkit forums known as Ekstemi
website: http://ekstemicraft.com
main: com.ekstemicraft.plugin.ecsync.ECSync
version: 1.0


  